[package]

name = "voxel-data"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
]

[lib]
name = "voxel_data"
path = "./src/mod.rs"

[dependencies]
cgmath = "0.12.*"
collision = "0.9.0"
log = "*"
rustc-serialize = "0.3.22"
